# _*_ coding: utf-8 _*_
#---------This file is generated by PcManager.----------------------------------------------------------------------
# 
#   File: 
#   Description: 
# 
#   Writer: 
#   Modify: 
#   vobject home page : http://vobject.skyhouseconsulting.com/
#   doc ref : http://vobject.skyhouseconsulting.com/epydoc/
#   installation : pip install vobject
#-----------------------------------------------------------------------------------------------------------------

import vobject

vcard = vobject.vCard()
vcard.add('n')
vcard.n.value = vobject.vcard.Name( family='Harris', given='Jeffrey' )
vcard.add('fn')
vcard.fn.value ='Jeffrey Harris'
vcard.add('email')
vcard.email.value = 'jeffrey@osafoundation.org'
vcard.serialize()
vcard.prettyPrint()

