# _*_ coding: utf-8 _*_

'''
Created on 2012. 10. 30.
@author: jaehyek
'''

dictPackageToAppName = {
"com.lge.appwidget.settings.bluetoothcontroller":"(W)Bluetooth Control",
"com.lge.sizechangable.calendar":"(W)Calendar",
"com.lge.appwidget.clock":"(W)Clock",
"com.lge.variousstyle.anlaogclock":"(W)Clock",
"com.lge.variousstyle.digitalclock":"(W)Clock",
"com.lge.sizechangable.favoritecontacts":"(W)Contacts",
"com.lge.dialerwidget":"(W)Dialer",
"com.lge.widget.dialerwidget":"(W)Dialer",
"com.lge.sizechangable.email":"(W)Email",
"com.lge.appwidget.flashlight":"(W)Flashlight",
"com.lge.appwidget.friends":"(W)Friends+",
"com.lge.intouch":"(W)In touch",
"com.lge.appwidget.singleaccess":"(W)Media in One",
"com.lge.sizechangable.memo":"(W)Memo",
"com.lge.sizechangable.message":"(W)Message",
"com.lge.appwidget.dualsimstatus":"(W)Multi SIM",
"com.lge.sizechangable.musicwidget.widget":"(W)Music",
"com.lge.myapplications":"(W)My Applications",
"com.lge.sizechangable.mycontacts":"(W)My Contacts",
"com.lge.appwidget.settings.mysettings":"(W)My Settings",
"com.lge.sizechangable.photoalbum":"(W)Photo Album",
"com.lge.sizechangable.photoframe":"(W)Photo Frame",
"com.lge.appwidget.settings.powercontrol":"(W)Power Control",
"com.lge.sizechangable.quicklearn":"(W)Quick Learn",
"com.lge.appwidget.lgsearch":"(W)Search",
"com.lge.sns":"(W)Social+",
"com.lge.android.stickynotes.widget":"(W)Sticky Notes",
"com.lge.theme.setting":"(W)Theme Changer",
"com.lge.appwidget.todayplus":"(W)Today+",
"com.lge.sizechangable.worldclock":"(W)World Clock",
"com.lge.lge3dgameconverter":"3D converter",
"com.lge.aab":"AAB",
"com.lge.yellowpages":"AAB",
"com.android.settingsaccessibility":"Accessibility Package",
"com.lge.clock":"Alarm / Clock",
"com.lge.animui":"Animation UI",
"com.lge.appbox.client":"Application Manager",
"com.lge.bnr":"Backup(LGBackup)",
"com.spritemobile.backup.lg":"Backup(LinkBackup)",
"com.box.android":"Box Net",
"com.android.caivs.app":"Caivs",
"com.android.calculator2":"Calculator",
"com.android.calendar":"Calendar",
"com.android.providers.calendar":"Calendar",
"com.lge.camera":"Camera",
"com.lge.cameratest":"Camera",
"com.lge.carhome":"Car Home",
"com.android.cellbroadcastreceiver":"CB",
"com.lge.smartshare.conn_wizard":"Connection Wizard",
"com.android.contacts":"Contacts",
"com.android.providers.contacts":"Contacts",
"com.lge.selftest":"Customer Self Test",
"com.lge.deskclock":"Desk Clock",
"com.lge.deskhome":"Desk Home",
"com.diotek.diodict2.lg":"Dictonary(전자사전)",
"com.diotek.diodict3.phone.lg.lgedict":"Dictonary(전자사전)",
"com.lge.oneseg":"DMB(TDMB/JDMB)",
"com.lge.tdmb":"DMB(TDMB/JDMB)",
"com.lge.dmf.admin":"Dmf Admin",
"com.android.providers.downloads":"Download",
"com.lgerp.smoothdrawer":"Drawing Effect",
"com.lge.eas":"EAS",
"com.lge.easyui":"Easy Home",
"com.lge.settings.easy":"EasySettings",
"com.android.email":"Email",
"com.android.exchange":"Email",
"com.lge.email":"Email",
"com.lge.snc":"Email",
"com.lge.emergencycontacts":"Emergency Contacts",
"com.facebook.katana":"Facebook",
"com.mcafee.android.familyprotection":"Family Protection",
"com.lge.filemanager":"File Manager",
"itectokyo.fileshare.ics20":"File Share",
"com.lge.sizechangable.finance":"Finance/(W)Finance",
"com.lge.fmradio":"FM Radio",
"com.lge.FmcCall":"FMC",
"com.hy.system.fontserver":"Font Server",
"com.android.gallery3d":"Gallery",
"com.lge.gestureanswering":"Gesture Answering",
"com.lge.homeselector":"Home Selector",
"com.lge.sso.ssoclient":"Hux App",
"com.lge.vvm":"Hux App",
"com.lge.vzw.bua":"Hux App",
"com.motricity.verizon.ssodownloadable":"Hux App",
"arcsoft.android.photoeditor":"Image Editor",
"com.lge.ime":"IME",
"com.lge.lgmits":"IMEI Tracker",
"com.android.browser":"Internet(Browser)",
"com.android.providers.partnerbookmarks":"Internet(Browser)",
"com.lge.launcher2":"Launcher (LG Home)",
"com.lge.defaultaccount":"LG Default Account",
"com.lge.ds":"LG DS Library",
"com.lge.lginstallservies":"LG Install Service",
"com.android.dreams.phototable":"LG Photo Table",
"com.lg.apps.cubeapp":"LG Smart World",
"com.lge.apps.jp.phone":"LG Smart World",
"com.lge.lgworld":"LG Smart World",
"com.lge.tagplus.ui":"LG TAG+",
"com.lge.tangible":"LG Tangible IO",
"com.lg.apps.centerapp":"LG전자 서비스(LG Counseling)",
"com.lge.lifestream":"Life Stream",
"com.android.galaxy4":"Live Wallpaper",
"com.android.magicsmoke":"Live Wallpaper",
"com.android.musicvis":"Live Wallpaper",
"com.android.noisefield":"Live Wallpaper",
"com.android.phasebeam":"Live Wallpaper",
"com.android.wallpaper":"Live Wallpaper",
"com.android.wallpaper.holospiral":"Live Wallpaper",
"com.android.wallpaper.livepicker":"Live Wallpaper",
"com.lge.chargingwallpaper.fireflies":"Live Wallpaper",
"com.lge.chargingwallpaper.gentlybubblingwatercw":"Live Wallpaper",
"com.lge.chargingwallpaper.nightscape":"Live Wallpaper",
"com.lge.chargingwallpaper.picker":"Live Wallpaper",
"com.lge.chargingwallpaper.risingtide":"Live Wallpaper",
"com.lge.livewallpaper.birdandcities":"Live Wallpaper",
"com.lge.livewallpaper.feather":"Live Wallpaper",
"com.lge.livewallpaper.marionette":"Live Wallpaper",
"com.lge.livewallpaper.multiphoto":"Live Wallpaper",
"com.lge.livewallpaper.polarbear":"Live Wallpaper",
"com.lge.livewallpaper.prince":"Live Wallpaper",
"com.lge.livewallpaper.prototype":"Live Wallpaper",
"com.lge.livewallpaper.seasonal":"Live Wallpaper",
"com.lge.wallpaper.tomsdinner":"Live Wallpaper",
"com.lge.lockscreen":"Lock Screen",
"com.lge.lockscreensettings":"Lock Screen",
"com.lge.pouchlockscreen":"Lock Screen",
"com.wsandroid.suite":"McAfee Mobile Security",
"com.lge.mhlmultimediahome":"Media Home",
"com.lge.app.richnote":"Memo",
"com.lge.memo":"Memo",
"com.android.mms":"Message",
"com.android.providers.telephony":"Message",
"com.lge.message":"Message",
"com.lge.voicemai":"Message",
"com.lge.mlt":"MLT",
"com.lge.mobileprint":"Mobile Print",
"com.lge.music":"Music",
"com.lge.myphonebook":"My Phonebook",
"com.lge.sizechangable.news":"News/(W)News",
"com.lge.Notebook":"Notebook",
"com.lge.android.owb":"Operator Wishbox",
"com.lge.osp":"OSP",
"com.lge.pcsyncui":"PC Suite",
"com.lge.sync":"PC Suite",
"com.android.phonenumberlocation":"Phone Number Location",
"com.infraware.polarisoffice":"Polaris Office",
"com.infraware.polarisviewer":"Polaris Viewer",
"com.lge.QuickClip":"QMemo",
"com.lge.ir.remote.settings":"QRemote",
"com.lge.qremote":"QRemote",
"com.lge.qshopping":"QShopping",
"com.cardcam.Qtranslator":"QTranslator",
"com.lge.quicklearn":"Quick Learn",
"com.lge.pa":"QVoice",
"com.lge.ims.rcsim":"RCS Chat/RCS Map",
"com.lge.ims.rcsstarter":"RCS Starter",
"com.rsupport.rs.activity.lge":"Remote Call",
"com.lge.roamingsettings":"Roaming Settings Kr",
"com.lge.safetycare":"Safety Care",
"com.lge.rendermain":"Scene Renderer",
"com.lge.screenrecord":"Screen Recorder",
"com.android.providers.settings":"Settings",
"com.android.settings":"Settings",
"itectokyo.sharegenie.app":"Share Genie",
"com.lge.simplehome":"Simple Home",
"com.lge.slideaside":"Slide Aside",
"com.lge.smartsettings":"Smart Settings",
"com.lge.smartshare.conn_wizard":"SmartShare Manager",
"com.android.LGSetupWizard":"Startup Wizard",
"com.android.LGSetupWizardApp":"Startup Wizard",
"com.lge.AppSetupWizard":"Startup Wizard",
"com.lge.stkfake":"Stk Fake",
"com.lge.streamingplayer":"Streaming Player",
"com.lge.sui.widget":"SUI",
"com.lge.lmk":"Task Manager",
"com.lge.task":"Tasks",
"com.twitter.android":"Twitter",
"com.lge.appcleanup":"Unused Apps",
"com.lge.helpcenter":"User Guide(사용 설명서)",
"com.ahnlab.msecurity2":"V3",
"com.lge.videotool":"VidClip",
"com.lge.vt":"Video Call",
"com.muvee.vea":"Video Editor",
"com.muvee.studio":"Video Wiz",
"com.lge.videoplayer":"Videos",
"com.android.phone":"Voice Call",
"com.lge.voicecommand":"Voice Command",
"com.android.voicedialer":"Voice Dialer",
"com.lge.voicerecorder":"Voice Recorder",
"com.lge.ltecall":"VoLTE",
"com.ipsec.vpnclient":"Vpn Client",
"com.lge.vmemo":"Vu:Talk",
"com.lge.wapservice":"Wap Service",
"com.lge.sizechangable.weather":"Weather/(W)Weather",
"itectokyo.wificastlite":"Wifi Share",
"com.lge.keepscreenon":"Wise Screen",
"com.Wo3G":"Wo3G",
"com.jiubang.goscreenlock":"Go락커",
"com.gau.go.launcherex":"GO 런처 EX ",
"com.nhn.android.search":"네이버 Search",
"com.cashslide":"캐시슬라이드",
"com.kakao.story":"카카오스토리",
"com.kakao.talk":"카카오톡",
"com.lge.allautotest":"LG autotest",
"com.linktomorrow.windrunner":"윈드러너 for Kakao",
"com.cjenm.chachacha":"다함께 차차차 for Kakao",
"com.patistudio.milc4kakao":"아이러브커피 for Kakao",
"com.sundaytoz.mobile.anipang.google.service":"애니팡 for Kakao",
"com.google.android.youtube":"Youtube",
"com.lge.hiddenmenu":"LG hiddenmenu",
"com.cjenm.kittypong":"다함께 퐁퐁퐁 for Kakao",
"net.daum.android.daum":"다음 - Daum",
"com.NextFloor.DragonFlightKakao":"드래곤 플라이트 for Kakao",
"kr.co.nowcom.mobile.afreeca":"아프리카TV",
"com.nhn.android.webtoon":"네이버 웹툰",
"com.android.chrome":"크롬 Browser",
"kr.co.feverstudio.apps.everytown":"에브리타운 for Kakao",
"com.nhn.android.navercafe":"네이버 카페",
"com.buzzvil.adhours":"애드아워스",
"kr.co.appdisco.lattescreen":"라떼스크린",
"com.square_enix.million_kr":"밀리언아서",
"com.skt.skaf.l001mtm091":"T Map",
"com.nhncorp.fishisland":"피쉬아일랜드",
"net.daum.android.cafe":"다음카페",
"com.com2us.tinyfarm.normal.freefull.google.global.android.common":"타이니팜",
"com.raongames.bouneball":"바운스볼",
"com.nhncorp.wooparoomountain":"우파루마운틴 for Kakao",
"com.lx.launcher8":"Launcher 8",
"com.mojang.minecraftpe":"Minecraft",
"com.picneko.warstory":"워스토리 for kakao",
"com.sundaytoz.mobile.anisachun.google.service":"애니팡 사천성 for Kakao",
"com.wemade.TouchFighter":"터치파이터 for Kakao",
"com.teslacoilsw.widgetlocker":"WidgetLocker 잠금화면",
"com.com2us.heroeswar.kakao.freefull.google.global.android.common":"히어로즈워 for Kakao",
"com.mxtech.videoplayer.ad":"MX 플레이어",
"com.hotdog.tinybattle":"모두의 게임 for Kakao",
"com.uplus.onphone":"U+ 폰",
"net.daum.android.air":"마이피플",
"com.jce.RuleTheSky":"Rule the Sky",
"com.nate.android.portalmini":"네이트",
"com.ftt.hwal_kakao":"활 for Kakao",
"com.fincon.hh":"헬로히어로 for Kakao",
"com.koramgame.play.zhkr":"암드 히어로즈",
"com.iloen.melon":"멜론",
"kr.co.vcnc.android.couple":"비트윈",
"jp.naver.line.android":"네이버 라인",
"com.lguplus.rms":"미러콜"
}

listLGApps = [
"com.lguplus.rms",
"com.lge.appwidget.settings.bluetoothcontroller",
"com.lge.sizechangable.calendar",
"com.lge.appwidget.clock",
"com.lge.variousstyle.anlaogclock",
"com.lge.variousstyle.digitalclock",
"com.lge.sizechangable.favoritecontacts",
"com.lge.dialerwidget",
"com.lge.widget.dialerwidget",
"com.lge.sizechangable.email",
"com.lge.appwidget.flashlight",
"com.lge.appwidget.friends",
"com.lge.intouch",
"com.lge.appwidget.singleaccess",
"com.lge.sizechangable.memo",
"com.lge.sizechangable.message",
"com.lge.appwidget.dualsimstatus",
"com.lge.sizechangable.musicwidget.widget",
"com.lge.myapplications",
"com.lge.sizechangable.mycontacts",
"com.lge.appwidget.settings.mysettings",
"com.lge.sizechangable.photoalbum",
"com.lge.sizechangable.photoframe",
"com.lge.appwidget.settings.powercontrol",
"com.lge.sizechangable.quicklearn",
"com.lge.appwidget.lgsearch",
"com.lge.sns",
"com.lge.android.stickynotes.widget",
"com.lge.theme.setting",
"com.lge.appwidget.todayplus",
"com.lge.sizechangable.worldclock",
"com.lge.lge3dgameconverter",
"com.lge.aab",
"com.lge.yellowpages",
"com.android.settingsaccessibility",
"com.lge.clock",
"com.lge.animui",
"com.lge.appbox.client",
"com.lge.bnr",
"com.spritemobile.backup.lg",
"com.box.android",
"com.android.caivs.app",
"com.android.calculator2",
"com.android.calendar",
"com.android.providers.calendar",
"com.lge.camera",
"com.lge.cameratest",
"com.lge.carhome",
"com.android.cellbroadcastreceiver",
"com.lge.smartshare.conn_wizard",
"com.android.contacts",
"com.android.providers.contacts",
"com.lge.selftest",
"com.lge.deskclock",
"com.lge.deskhome",
"com.diotek.diodict2.lg",
"com.diotek.diodict3.phone.lg.lgedict",
"com.lge.oneseg",
"com.lge.tdmb",
"com.lge.dmf.admin",
"com.android.providers.downloads",
"com.lgerp.smoothdrawer",
"com.lge.eas",
"com.lge.easyui",
"com.lge.settings.easy",
"com.android.email",
"com.android.exchange",
"com.lge.email",
"com.lge.snc",
"com.lge.emergencycontacts",
"com.facebook.katana",
"com.mcafee.android.familyprotection",
"com.lge.filemanager",
"itectokyo.fileshare.ics20",
"com.lge.sizechangable.finance",
"com.lge.fmradio",
"com.lge.FmcCall",
"com.hy.system.fontserver",
"com.android.gallery3d",
"com.lge.gestureanswering",
"com.lge.homeselector",
"com.lge.sso.ssoclient",
"com.lge.vvm",
"com.lge.vzw.bua",
"com.motricity.verizon.ssodownloadable",
"arcsoft.android.photoeditor",
"com.lge.ime",
"com.lge.lgmits",
"com.android.browser",
"com.android.providers.partnerbookmarks",
"com.lge.launcher2",
"com.lge.defaultaccount",
"com.lge.ds",
"com.lge.lginstallservies",
"com.android.dreams.phototable",
"com.lg.apps.cubeapp",
"com.lge.apps.jp.phone",
"com.lge.lgworld",
"com.lge.tagplus.ui",
"com.lge.tangible",
"com.lg.apps.centerapp",
"com.lge.lifestream",
"com.android.galaxy4",
"com.android.magicsmoke",
"com.android.musicvis",
"com.android.noisefield",
"com.android.phasebeam",
"com.android.wallpaper",
"com.android.wallpaper.holospiral",
"com.android.wallpaper.livepicker",
"com.lge.chargingwallpaper.fireflies",
"com.lge.chargingwallpaper.gentlybubblingwatercw",
"com.lge.chargingwallpaper.nightscape",
"com.lge.chargingwallpaper.picker",
"com.lge.chargingwallpaper.risingtide",
"com.lge.livewallpaper.birdandcities",
"com.lge.livewallpaper.feather",
"com.lge.livewallpaper.marionette",
"com.lge.livewallpaper.multiphoto",
"com.lge.livewallpaper.polarbear",
"com.lge.livewallpaper.prince",
"com.lge.livewallpaper.prototype",
"com.lge.livewallpaper.seasonal",
"com.lge.wallpaper.tomsdinner",
"com.lge.lockscreen",
"com.lge.lockscreensettings",
"com.lge.pouchlockscreen",
"com.wsandroid.suite",
"com.lge.mhlmultimediahome",
"com.lge.app.richnote",
"com.lge.memo",
"com.android.mms",
"com.android.providers.telephony",
"com.lge.message",
"com.lge.voicemai",
"com.lge.mlt",
"com.lge.mobileprint",
"com.lge.music",
"com.lge.myphonebook",
"com.lge.sizechangable.news",
"com.lge.Notebook",
"com.lge.android.owb",
"com.lge.osp",
"com.lge.pcsyncui",
"com.lge.sync",
"com.android.phonenumberlocation",
"com.infraware.polarisoffice",
"com.infraware.polarisviewer",
"com.lge.QuickClip",
"com.lge.ir.remote.settings",
"com.lge.qremote",
"com.lge.qshopping",
"com.cardcam.Qtranslator",
"com.lge.quicklearn",
"com.lge.pa",
"com.lge.ims.rcsim",
"com.lge.ims.rcsstarter",
"com.rsupport.rs.activity.lge",
"com.lge.roamingsettings",
"com.lge.safetycare",
"com.lge.rendermain",
"com.lge.screenrecord",
"com.android.providers.settings",
"com.android.settings",
"itectokyo.sharegenie.app",
"com.lge.simplehome",
"com.lge.slideaside",
"com.lge.smartsettings",
"com.lge.smartshare.conn_wizard",
"com.android.LGSetupWizard",
"com.android.LGSetupWizardApp",
"com.lge.AppSetupWizard",
"com.lge.stkfake",
"com.lge.streamingplayer",
"com.lge.sui.widget",
"com.lge.lmk",
"com.lge.task",
"com.twitter.android",
"com.lge.appcleanup",
"com.lge.helpcenter",
"com.ahnlab.msecurity2",
"com.lge.videotool",
"com.lge.vt",
"com.muvee.vea",
"com.muvee.studio",
"com.lge.videoplayer",
"com.android.phone",
"com.lge.voicecommand",
"com.android.voicedialer",
"com.lge.voicerecorder",
"com.lge.ltecall",
"com.ipsec.vpnclient",
"com.lge.vmemo",
"com.lge.wapservice",
"com.lge.sizechangable.weather",
"itectokyo.wificastlite",
"com.lge.keepscreenon",
"com.Wo3G" ,
"com.lge.allautotest",
"com.lge.android.atservice",
"com.lge.android.hime",
"com.lge.android.oven",
"com.lge.android.smartdiagnosis.kr",
"com.lge.app.network_folder",
"com.lge.appbox.bridge",
"com.lge.artui",
"com.lge.battery.checker",
"com.lge.bdsapp",
"com.lge.clockweatherwidget",
"com.lge.drmlguservice",
"com.lge.fotopoly",
"com.lge.gnss.airtest",
"com.lge.gnss.xtradownload",
"com.lge.gnssposts",
"com.lge.hiddenmenu",
"com.lge.hiddenmenuko",
"com.lge.hms.remote",
"com.lge.ia.apps.iris",
"com.lge.ims",
"com.lge.ipsolute",
"com.lge.keyboxtest",
"com.lge.launcher2.theme.biz",
"com.lge.launcher2.theme.IIDX",
"com.lge.LauncherApp",
"com.lge.lgcloud.nscreen",
"com.lge.lgewhitethemesample",
"com.lge.lgexam",
"com.lge.lgfotaclient",
"com.lge.lglink.shield",
"com.lge.lgpodcast",
"com.lge.LGShuttleBusSchedule",
"com.lge.lgwelfare",
"com.lge.log",
"com.lge.lollipop",
"com.lge.magic",
"com.lge.media.lgbluetoothremote",
"com.lge.media.lgpocketphoto",
"com.lge.membership",
"com.lge.mountaink",
"com.lge.mpost.alime",
"com.lge.networkpostest",
"com.lge.opinet",
"com.lge.ota",
"com.lge.popic2",
"com.lge.readersworld",
"com.lge.retailmode",
"com.lge.settings.compatmode",
"com.lge.shutdownmonitor",
"com.lge.smartshare",
"com.lge.stabilitytest",
"com.lge.subwaymap",
"com.lge.texttranslator",
"com.lge.themebox",
"com.lge.themebox.themepackage_013",
"com.lge.themebox.themepackage_036",
"com.lge.themebox.themepackage_1100074",
"com.lge.themebox.themepackage_1100075",
"com.lge.themepark.JellyBean",
"com.lge.themepark.theme_20120711040945",
"com.lge.themepark.theme_20120711044911",
"com.lge.themepark.theme_20120711045035",
"com.lge.themepark.theme_20120711045154",
"com.lge.themepark.theme_20120711045303",
"com.lge.themepark.theme_20120711092618",
"com.lge.themepark.theme_20120712082556",
"com.lge.themepark.theme_20120712085325",
"com.lge.themepark.theme_20120712085728",
"com.lge.themepark.theme_20120712090200",
"com.lge.themepark.theme_20120908055540",
"com.lge.themepark.theme_20121024021048",
"com.lge.themepark.theme_20121108110754",
"com.lge.themepark.theme_20121120032226",
"com.lge.themepark.theme_20121120114348",
"com.lge.themepark.theme_20121124101915",
"com.lge.themepark.theme_20121202093617",
"com.lge.themepark.theme_20121203092753",
"com.lge.themepark.theme_20121205113947",
"com.lge.themepark.theme_20121209044648",
"com.lge.themepark.theme_20121210022650",
"com.lge.themepark.theme_20121212013034",
"com.lge.themepark.theme_20121213034103",
"com.lge.themepark.theme_20121213105821",
"com.lge.themepark.theme_20121217023620",
"com.lge.themepark.theme_20121217025446",
"com.lge.themepark.theme_20121217025819",
"com.lge.themepark.theme_20121217030112",
"com.lge.themepark.theme_20121217030753",
"com.lge.themepark.theme_20121217031141",
"com.lge.themepark.theme_20121217032128",
"com.lge.themepark.theme_20121217033215",
"com.lge.themepark.theme_20121217034821",
"com.lge.themepark.theme_20121217035029",
"com.lge.themepark.theme_20121217035246",
"com.lge.themepark.theme_20121217035616",
"com.lge.themepark.theme_20121217040159",
"com.lge.themepark.theme_20121217041048",
"com.lge.themepark.theme_20121217041248",
"com.lge.themepark.theme_20121217042635",
"com.lge.themepark.theme_20121217042900",
"com.lge.themepark.theme_20121217043118",
"com.lge.themepark.theme_20121217043443",
"com.lge.themepark.theme_20121217043929",
"com.lge.themepark.theme_20121217044130",
"com.lge.themepark.theme_20121217044718",
"com.lge.themepark.theme_20121217045030",
"com.lge.themepark.theme_20121217045517",
"com.lge.themepark.theme_20121217045735",
"com.lge.themepark.theme_20121217045902",
"com.lge.themepark.theme_20121217050543",
"com.lge.themepark.theme_20121218111845",
"com.lge.themepark.theme_20121218113239",
"com.lge.themepark.theme_20121218113629",
"com.lge.themepark.theme_20121218114344",
"com.lge.themepark.theme_20121218115011",
"com.lge.themepark.theme_20121218115256",
"com.lge.themepark.theme_20121218115521",
"com.lge.themepark.theme_20121218115813",
"com.lge.themepark.theme_20121218121022",
"com.lge.themepark.theme_20121218121256",
"com.lge.themepark.theme_20121218121702",
"com.lge.themepark.theme_20121218121931",
"com.lge.themepark.theme_20121218122231",
"com.lge.themepark.theme_20130101014604",
"com.lge.themepark.theme_20130106125009",
"com.lge.themepark.theme_20130117055811",
"com.lge.themepark.theme_20130124035101",
"com.lge.themepark.theme_20130220044729",
"com.lge.themepark.theme_20130220045006",
"com.lge.themepark.theme_20130220045315",
"com.lge.themepark.theme_20130221092029",
"com.lge.themepark.theme_20130222081317",
"com.lge.themepark.theme_20130222084336",
"com.lge.themepark.theme_20130222084552",
"com.lge.themepark.theme_20130222085124",
"com.lge.themepark.theme_20130222085411",
"com.lge.themepark.theme_20130222085622",
"com.lge.themepark.theme_20130222085833",
"com.lge.themepark.theme_20130222090248",
"com.lge.themepark.theme_20130222093807",
"com.lge.themepark.theme_20130222094031",
"com.lge.themepark.theme_20130222094233",
"com.lge.themepark.theme_20130222094437",
"com.lge.themepark.theme_20130222094913",
"com.lge.themepark.theme_20130222095109",
"com.lge.themepark.theme_20130222095700",
"com.lge.themepark.theme_20130222095904",
"com.lge.themepark.theme_20130222100224",
"com.lge.themepark.theme_20130222100419",
"com.lge.themepark.theme_20130222100815",
"com.lge.themepark.theme_20130225110711",
"com.lge.themepark.theme_20130306035601",
"com.lge.themepark.theme_20130306045505",
"com.lge.themepark.theme_20130306050854",
"com.lge.themepark.theme_20130306051110",
"com.lge.themepark.theme_20130306054817",
"com.lge.themepark.theme_20130306055220",
"com.lge.themepark.theme_miui",
"com.lge.tservice",
"com.lge.tv.nfcapps",
"com.lge.tv.remoteapps",
"com.lge.weekly",
"com.lge.whisen.WhisenAppLG",
"com.lge.wv.hidden"
]