# _*_ coding: utf-8 _*_

'''
Created on 2012. 7. 6.

@author: jaehyek
'''
listdictFilteringSympton = [
{"Filtering_YN":"N", "symptom_cd":"MAA", "symptom_desc":"3G 화상 통화 저조/안됨"}, 
{"Filtering_YN":"N", "symptom_cd":"MAB", "symptom_desc":"가변코드(사업본부 지정시 사용)"}, 
{"Filtering_YN":"N", "symptom_cd":"MAD", "symptom_desc":"기능 오동작"}, 
{"Filtering_YN":"N", "symptom_cd":"MAE", "symptom_desc":"라디오 기능불량"}, 
{"Filtering_YN":"N", "symptom_cd":"MAF", "symptom_desc":"메모리 인식/동작불량(내.외장)"}, 
{"Filtering_YN":"N", "symptom_cd":"MAG", "symptom_desc":"메세지(SMS,MMS) 동작불량"}, 
{"Filtering_YN":"N", "symptom_cd":"MAH", "symptom_desc":"배터리 대기 시간 짧음"}, 
{"Filtering_YN":"N", "symptom_cd":"MAJ", "symptom_desc":"배터리 부풀어 오름"}, 
{"Filtering_YN":"N", "symptom_cd":"MAL", "symptom_desc":"버튼 불량(터치 제외)"}, 
{"Filtering_YN":"N", "symptom_cd":"MAM", "symptom_desc":"버튼 배경 조명 불량"}, 
{"Filtering_YN":"N", "symptom_cd":"MAN", "symptom_desc":"효과음 불량(버튼음,슬라이드음등)"}, 
{"Filtering_YN":"N", "symptom_cd":"MAP", "symptom_desc":"벨소리 무감"}, 
{"Filtering_YN":"N", "symptom_cd":"MAQ", "symptom_desc":"벨소리 작음"}, 
{"Filtering_YN":"N", "symptom_cd":"MAR", "symptom_desc":"벨소리 잡음"}, 
{"Filtering_YN":"N", "symptom_cd":"MAT", "symptom_desc":"블루투스 동작불량"}, 
{"Filtering_YN":"Y", "symptom_cd":"MAU", "symptom_desc":"기타사용중 동작 멈춤"}, 
{"Filtering_YN":"N", "symptom_cd":"MAV", "symptom_desc":"사이드 버튼 동작 불량"}, 
{"Filtering_YN":"N", "symptom_cd":"MAW", "symptom_desc":"사진/동영상 재생 불량"}, 
{"Filtering_YN":"N", "symptom_cd":"MAX", "symptom_desc":"송수신 저조 및 안됨"}, 
{"Filtering_YN":"N", "symptom_cd":"MAY", "symptom_desc":"송수신 통화중 끊김"}, 
{"Filtering_YN":"N", "symptom_cd":"MAZ", "symptom_desc":"송화음 무감"}, 
{"Filtering_YN":"N", "symptom_cd":"MBA", "symptom_desc":"송화음 작음"}, 
{"Filtering_YN":"N", "symptom_cd":"MBB", "symptom_desc":"송화음 잡음/끊김"}, 
{"Filtering_YN":"N", "symptom_cd":"MBC", "symptom_desc":"수화음 무감"}, 
{"Filtering_YN":"N", "symptom_cd":"MBD", "symptom_desc":"수화음 작음"}, 
{"Filtering_YN":"N", "symptom_cd":"MBE", "symptom_desc":"수화음 잡음/끊김"}, 
{"Filtering_YN":"N", "symptom_cd":"MBF", "symptom_desc":"알람/모닝콜 안됨 및 오동작"}, 
{"Filtering_YN":"N", "symptom_cd":"MBJ", "symptom_desc":"사업자 부가서비스 오류(뱅크온,인터넷.위젯등)"}, 
{"Filtering_YN":"N", "symptom_cd":"MBK", "symptom_desc":"적외선(IRDA) 기능불량"}, 
{"Filtering_YN":"Y", "symptom_cd":"MBM", "symptom_desc":"전원 부팅중 멈춤(Lock up)"}, 
{"Filtering_YN":"Y", "symptom_cd":"MBN", "symptom_desc":"전원 사용중 on/off (Reset)"}, 
{"Filtering_YN":"Y", "symptom_cd":"MBP", "symptom_desc":"전원 사용/대기중 꺼짐"}, 
{"Filtering_YN":"Y", "symptom_cd":"MBQ", "symptom_desc":"전원 초기 무한 Reset"}, 
{"Filtering_YN":"N", "symptom_cd":"MBR", "symptom_desc":"전원무감"}, 
{"Filtering_YN":"N", "symptom_cd":"MBS", "symptom_desc":"진동 안됨 및 약함"}, 
{"Filtering_YN":"N", "symptom_cd":"MBT", "symptom_desc":"충전안됨(깜빡임)"}, 
{"Filtering_YN":"N", "symptom_cd":"MBU", "symptom_desc":"카메라 사진/동영상 저장안됨"}, 
{"Filtering_YN":"N", "symptom_cd":"MBV", "symptom_desc":"카메라 플래쉬불량"}, 
{"Filtering_YN":"Y", "symptom_cd":"MBW", "symptom_desc":"카메라 사용 중 멈춤"}, 
{"Filtering_YN":"N", "symptom_cd":"MBX", "symptom_desc":"카메라 화질/화소불량(화상포함)"}, 
{"Filtering_YN":"N", "symptom_cd":"MBY", "symptom_desc":"카메라 회전안됨"}, 
{"Filtering_YN":"N", "symptom_cd":"MBZ", "symptom_desc":"카메라무감(화상포함)"}, 
{"Filtering_YN":"N", "symptom_cd":"MCB", "symptom_desc":"폴더/슬라이드/스윙 인식 안됨"}, 
{"Filtering_YN":"N", "symptom_cd":"MCD", "symptom_desc":"DMB TV 수신 끊김"}, 
{"Filtering_YN":"N", "symptom_cd":"MCE", "symptom_desc":"DMB TV 수신 안됨"}, 
{"Filtering_YN":"N", "symptom_cd":"MCF", "symptom_desc":"FM TRANSMITTER 불량"}, 
{"Filtering_YN":"N", "symptom_cd":"MCG", "symptom_desc":"GPS 불량"}, 
{"Filtering_YN":"N", "symptom_cd":"MCH", "symptom_desc":"Main LCD 백라이트 안들어옴"}, 
{"Filtering_YN":"N", "symptom_cd":"MCJ", "symptom_desc":"Main LCD 화면화질(변색,멍듬)"}, 
{"Filtering_YN":"N", "symptom_cd":"MCK", "symptom_desc":"Main LCD 화면무감"}, 
{"Filtering_YN":"N", "symptom_cd":"MCL", "symptom_desc":"Main LCD 화면백화(하얗게 나옴)"}, 
{"Filtering_YN":"N", "symptom_cd":"MCM", "symptom_desc":"Main LCD 화면줄감"}, 
{"Filtering_YN":"N", "symptom_cd":"MCN", "symptom_desc":"MP3 기능불량(재생,다운)"}, 
{"Filtering_YN":"N", "symptom_cd":"MCP", "symptom_desc":"MP3 음질불량"}, 
{"Filtering_YN":"N", "symptom_cd":"MCQ", "symptom_desc":"NO SVC"}, 
{"Filtering_YN":"N", "symptom_cd":"MCS", "symptom_desc":"SUB LCD 무감"}, 
{"Filtering_YN":"N", "symptom_cd":"MCT", "symptom_desc":"SUB LCD 백라이트 안들어옴"}, 
{"Filtering_YN":"N", "symptom_cd":"MCU", "symptom_desc":"SUB LCD 줄감"}, 
{"Filtering_YN":"N", "symptom_cd":"MCV", "symptom_desc":"SUB LCD 화질(변색,멍듬)"}, 
{"Filtering_YN":"N", "symptom_cd":"MCW", "symptom_desc":"SUB LCD 화면백화(하얗게 나옴)"}, 
{"Filtering_YN":"N", "symptom_cd":"MCX", "symptom_desc":"DMB 채널 검색 안됨"}, 
{"Filtering_YN":"N", "symptom_cd":"MDA", "symptom_desc":"동영상/녹음 재생음불량"}, 
{"Filtering_YN":"N", "symptom_cd":"MDB", "symptom_desc":"다운 콘텐츠 오동작(게임,배경화면 등)"}, 
{"Filtering_YN":"N", "symptom_cd":"MDC", "symptom_desc":"액정깨짐"}, 
{"Filtering_YN":"N", "symptom_cd":"MDD", "symptom_desc":"USIM 인식불량"}, 
{"Filtering_YN":"N", "symptom_cd":"MDE", "symptom_desc":"터치 버튼 무감"}, 
{"Filtering_YN":"N", "symptom_cd":"MDF", "symptom_desc":"터치 버튼 오동작"}, 
{"Filtering_YN":"N", "symptom_cd":"MDG", "symptom_desc":"3G 화상 통화중 끊김"}, 
{"Filtering_YN":"N", "symptom_cd":"MDH", "symptom_desc":"3G 화상 수화음 무감"}, 
{"Filtering_YN":"N", "symptom_cd":"MDJ", "symptom_desc":"3G 화상 수화음 작음"}, 
{"Filtering_YN":"N", "symptom_cd":"MDK", "symptom_desc":"3G 화상 송화음 무감"}, 
{"Filtering_YN":"N", "symptom_cd":"MDL", "symptom_desc":"3G 화상 송화음 작음"}, 
{"Filtering_YN":"N", "symptom_cd":"MDM", "symptom_desc":"3G 화상 수화음 잡음/끊김"}, 
{"Filtering_YN":"N", "symptom_cd":"MDN", "symptom_desc":"3G 화상 송화음 잡음/끊김"}, 
{"Filtering_YN":"Y", "symptom_cd":"MDP", "symptom_desc":"DMB 사용중멈춤"}, 
{"Filtering_YN":"N", "symptom_cd":"MDW", "symptom_desc":"FOTA후 오동작불량"}, 
{"Filtering_YN":"N", "symptom_cd":"MDX", "symptom_desc":"인터넷 접속불량"}, 
{"Filtering_YN":"N", "symptom_cd":"MDY", "symptom_desc":"Wifi동작불량"}, 
{"Filtering_YN":"N", "symptom_cd":"MDZ", "symptom_desc":"스마트폰 에러문구발생(Sorry팝업)"}, 
{"Filtering_YN":"N", "symptom_cd":"MEA", "symptom_desc":"스마트폰 어플리케이션 동작불량"}, 
{"Filtering_YN":"N", "symptom_cd":"MEB", "symptom_desc":"주소록(폰북) 오류불량"}, 
{"Filtering_YN":"N", "symptom_cd":"MEC", "symptom_desc":"PC Sync 불량(PC연결안됨)"}, 
{"Filtering_YN":"N", "symptom_cd":"MED", "symptom_desc":"근접/조도/가속센서 불량"}, 
{"Filtering_YN":"N", "symptom_cd":"MEE", "symptom_desc":"HDMI 불량"}, 
{"Filtering_YN":"N", "symptom_cd":"MEF", "symptom_desc":"송수화음 동시 무감"}, 
{"Filtering_YN":"N", "symptom_cd":"MEG", "symptom_desc":"발열"}, 
{"Filtering_YN":"Y", "symptom_cd":"MGA", "symptom_desc":"업그레이드중 멈춤"}, 
{"Filtering_YN":"Y", "symptom_cd":"MGB", "symptom_desc":"대기중 멈춤"}, 
{"Filtering_YN":"Y", "symptom_cd":"MGC", "symptom_desc":"어플사용중 멈춤"}, 
{"Filtering_YN":"N", "symptom_cd":"MGD", "symptom_desc":"문자사용중 멈춤"}, 
{"Filtering_YN":"Y", "symptom_cd":"MGE", "symptom_desc":"인터넷 사용중 멈춤"}, 
{"Filtering_YN":"Y", "symptom_cd":"MGF", "symptom_desc":"Wifi 사용중멈춤"}, 
{"Filtering_YN":"Y", "symptom_cd":"MGG", "symptom_desc":"MP3 사용중멈춤"}, 
{"Filtering_YN":"Y", "symptom_cd":"MGH", "symptom_desc":"동영상 사용중멈춤"}, 
{"Filtering_YN":"Y", "symptom_cd":"MGJ", "symptom_desc":"DMB 사용중멈춤"}, 
{"Filtering_YN":"Y", "symptom_cd":"MGK", "symptom_desc":"통화 사용중멈춤"}, 
{"Filtering_YN":"Y", "symptom_cd":"MGL", "symptom_desc":"폰메뉴 동작중멈춤"}, 
{"Filtering_YN":"N", "symptom_cd":"MKN", "symptom_desc":"3G 네트워크 표시안됨"}
]
